version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: userAuth
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5433:5432"

  fastapi-app:
    build: .
    container_name: fastapi-app
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://postgres:1234@db:5432/userAuth
    ports:
      - "8001:8001"
    command: >
      sh -c "sleep 5 && uvicorn main:app --host 0.0.0.0 --port 8001 --reload"

volumes:
  pgdata:
